---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  golint:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - app/**
  - Gemfile.lock
  - lib/**
  - "**.css"
  - "**.erb"
  - "**.go"
  - "**.haml"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
